1)Numpy is a python Library.
2)Numpy is used for working with arrays.
3)Numpy is short for Numerical Python.
4)It also has functions for working in domain like Linear Algebra,Fourier Transforms and matrices.

*)Why Use Numpy

1)In python,lists serve the purpose of arrays and they are slow to process.
2)Numpy aims to provide array object that is 50x faster than lists.
3)Array object in numpy is called (ndarray).
4)ndarray provides lot of supporting functions that make easy working with ndarray.

*In Python, lists are stored as arrays of references to their elements, rather than storing the elements themselves directly in contiguous memory locations. This means that the elements of a list can be scattered across memory, and they don't necessarily have to be stored in contiguous memory locations.

Each element of the list is a reference to the actual object stored in memory. So, even though the references themselves are stored in contiguous memory locations, the objects they point to can be located anywhere in memory.

This approach provides flexibility in terms of memory allocation and management, as elements can be added or removed from the list without needing to allocate or deallocate contiguous memory blocks. However, it can also lead to slightly slower performance compared to languages where arrays are stored contiguously, especially when accessing elements randomly.

Why is NumPy Faster Than Lists?
NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

This behavior is called locality of reference in computer science.

This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.

*Numpy is partially written in python and those parts requires faster computation are written in c or c++.

python and pip are necessary to install mumpu

In [2]:
pip install numpy #command to install numpy

Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np #command to import numpy after installing the numpy library.

Here as keyword is used when we want to refer to alias name

np is alias name for numpy and it can be anything.

In [7]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


To check version of numpy

In [8]:
print(np.__version__)

1.24.3


The array object in numpy array is called as ndarray

we can create a ndarray object by using array() function

In [9]:
array=np.array([1,2,3,4,5])
print(np.array)

<built-in function array>


In [10]:
print(array)
print(type(array))

[1 2 3 4 5]
<class 'numpy.ndarray'>


To create a ndarray we can pass a list,type or any array-like object into the array() method and it will be converted into ndarray.

Dimensional Arrays
-------------------
0-Dimensional Arrays
o-D arrays or scalars are the elements in an array.Each value in an array is 0-dimensional.

In [14]:
arr=np.array(42)
print(arr)
print(type(arr))

42
<class 'numpy.ndarray'>


1-d Arrays
    1-D arrays or uidirectional arrays has direction but no magnitude.

In [12]:
array=np.array([1,2,3,4,5])
print(array)

[1 2 3 4 5]


2-D Arrays
An array that has 1-D arrays as its elements is called a 2-D array.

These are often used to represent matrix or 2nd order tensors.

In [16]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
3-D arrays
An array that has 2-D arrays (matrices) as its elements is called 3-D array.

These are often used to represent a 3rd order tensor.

In [21]:
arr=np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[11,12,13,14,15],[16,17,18,19,20]]])
print(arr)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]


To Check number of dimensions  use ndim

In [22]:
print(arr.ndim)

3


In [23]:
arr=np.array([1,2,3,4],ndmin=5)
print(arr)

[[[[[1 2 3 4]]]]]


In [24]:
print(arr[0])

[[[[1 2 3 4]]]]


In [28]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,5]])
print(arr[0,4])

5


In [29]:
arr=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr[0,1,2])

6


Array Slicing
-------------------
array_name[start,end]
or
array_name[start,end,step]

Numpy DataTypes
--------------------------
strings,integer,float,boolean,complex

Data Types in Numpy
-------------------------------
i- integer
u-unsigned integer
b-boolean
f-float
c-complex float
m-timedelta
M-datetime
O-object
S-string
U-unicode string 

In [30]:
arr=np.array([1,2,3,4,5])
print(arr.dtype)

int32


In [33]:
arr1=np.array(['apple','banana','guava'])
print(arr1.dtype)

<U6


In [38]:
arr1=np.array([1,2,3,4,5],dtype='U')
print(arr1)

['1' '2' '3' '4' '5']


In [45]:
arr=np.array([1.1,2.2,3.3])
newarr=arr.astype(int)
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [1]:
import numpy as np

In [7]:
arr=np.array([1,2,3,4])
print(arr[0:2:1])

[1 2]


In [14]:
arr=np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
print(arr)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


In [27]:
#zero dimnesional Array creation
arr1=np.array(1)
print(arr1)
print(arr1.shape)
print(arr1.itemsize)
print(arr1.size)
print(arr1.data)
print(arr1.dtype)
print(arr1.ndim)

1
()
4
1
int32
0


In [33]:
#1-dimensional array creation
arr2=np.array([1],dtype='int64')
print(arr2)
print(arr2.shape)
print(arr2.size)
print(arr2.data)
print(arr2.itemsize)
print(arr2.ndim)
print(arr2.dtype)

[1]
(1,)
1
8
1
int64


In [36]:
#1-dimensional array creation
arr3=np.array([1,2])
print(arr3.shape)#outputs:(2,)
print(arr3.size)#2
print(arr3.itemsize)#4 for int32
print(arr3.ndim)#1
print(arr3.dtype)#int
print(arr3.data)

(2,)
2
4
1
int32


In [43]:
#2-dimensional array creation
arr4=np.array([[1,2,3]])
print(arr4.shape)
print(arr4.itemsize)
print(arr4.dtype)
print(arr4.ndim)

(1, 3)
4
int32
2


In [60]:
#2-dimensional array creation
arr4=np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
print(arr4)
print(arr4.shape)
print(arr4.itemsize)
print(arr4.dtype)
print(arr4.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
4
int32
2


In [61]:
#3-dimensional array
arr6=np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]],
    [[13,14,15],[16,17,18]]
])
print(arr6)
print(arr6.shape)
print(arr6.ndim)
print(arr6.size)
print(arr6.itemsize)
print(arr6.dtype)
print(arr6.data)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
(3, 2, 3)
3
18
4
int32


In [64]:
#higher dimensional array
#3-dimensional array
arr6=np.array([[
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]],
    [[13,14,15],[16,17,18]]],
    [
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]],
    [[13,14,15],[16,17,18]]]
])
print(arr6)
print(arr6.shape)

[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]

  [[13 14 15]
   [16 17 18]]]


 [[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]

  [[13 14 15]
   [16 17 18]]]]
(2, 3, 2, 3)


In [71]:
arr=np.array(40)
print(arr[()])
#this is same for both positive and negative indexing

40


In [72]:
#o-dimensional array slicing
arr=np.array(0)
print(arr)
#this does not have slicing because it has 0-dimensions

0


In [76]:
#1-dimensional array slicing
arr=np.array([1,2,3,4,5])

print(arr[0:5])#forward postive slicing

print(arr[-1:-6:])#backward negative slicing


[1 2 3 4 5]
[]


In [77]:
print(arr[-6:-1])

[1 2 3 4]


In [85]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Positive indexing iteration
for i in range(0,arr_2d.shape[0]):
    for j in range(0,arr_2d.shape[1]):
        print(arr_2d[i, j],end=" ")
    print()


1 2 3 
4 5 6 
7 8 9 


In [87]:
# Negative indexing iteration
for i in range(-1, -arr_2d.shape[0]-1, -1):
    for j in range(-1, -arr_2d.shape[1]-1, -1):
        print(arr_2d[i, j],end=" ")
    print()

9 8 7 
6 5 4 
3 2 1 


In [88]:
arr=np.arange(0,5,1,dtype='int')
print(arr)

[0 1 2 3 4]


In [95]:
print(np.zeros((3,3),dtype=int,order='F'))

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [97]:
print(np.ones((3,4)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [99]:
arr=np.full((2,3),4,order='C')
print(arr)

[[4 4 4]
 [4 4 4]]


In [110]:
print(np.arange(0,12).reshape(3,-1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [116]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Repeat values along axis 0 (rows)
repeated_arr_axis0 = np.repeat(arr, 3, axis=0)

# Repeat values along axis 1 (columns)
repeated_arr_axis1 = np.repeat(arr, 3, axis=1)

print("Original Array:")
print(arr)
print("Repeated Array along axis 0 (rows):")
print(repeated_arr_axis0)
print("Repeated Array along axis 1 (columns):")
print(repeated_arr_axis1)


Original Array:
[[1 2 3]
 [4 5 6]]
Repeated Array along axis 0 (rows):
[[1 2 3]
 [1 2 3]
 [1 2 3]
 [4 5 6]
 [4 5 6]
 [4 5 6]]
Repeated Array along axis 1 (columns):
[[1 1 1 2 2 2 3 3 3]
 [4 4 4 5 5 5 6 6 6]]


In [117]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])
concatenated_arr = np.concatenate((arr1, arr2), axis=0)
print(concatenated_arr)


[[1 2]
 [3 4]
 [5 6]]


In [120]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
stacked_arr = np.vstack((arr1, arr2))
print(stacked_arr)


[[1 2 3]
 [4 5 6]]


In [121]:
import numpy as np

arr1 = np.array([[1], [2], [3]])
arr2 = np.array([[4], [5], [6]])
stacked_arr = np.hstack((arr1, arr2))
print(stacked_arr)


[[1 4]
 [2 5]
 [3 6]]


In [122]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

concatenated_arr = np.r_[arr1, arr2]
print(concatenated_arr)


[1 2 3 4 5 6]


In [6]:
import numpy as np
arr=np.array([1,2,3,4])
power=np.array([2,2,2,2])
result=np.power(arr,power)
res=np.power(arr,3)
print(result,res)

[ 1  4  9 16] [ 1  8 27 64]


In [7]:
import numpy as np

arr = np.array([1, 3, 6, 10])
diff_result = np.diff(arr)

print(diff_result)


[2 3 4]


In [15]:
import numpy as np

# Define arrays
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([4, 3, 2, 1])

# Concatenate arr1 and arr2
concatenated_arr = np.concatenate((arr1, arr2))

# Sort the concatenated array along axis 0
sorted_arr = np.sort(concatenated_arr, axis=0)

# Reverse the sorted array
reversed_arr = sorted_arr[::-1]

print(reversed_arr)


[4 4 3 3 2 2 1 1]
