# unfunc Introduction

In [ ]:
#ufuncs stands for universal functions.
#ufuncs are numpy functions that operate on ndarray object.

In [ ]:
#ufuncs are used to implement vectorization in numpy which is faster than iterating over elements.
#For computation ufuncs provide methods like accumulate,reduce etc... and broadcasting also.
#ufuncs also take additional arguments like:

#1)where boolean array or condition defining where the operations should take place.

#2)dtype defining the return type of elements.

#3)out output array where the return value should be copied.

In [ ]:
#Vectorization
#--------------
#converting iterative statements into vector based operations is called vectorization.

In [1]:
#Add the elements of Two lists
x=[1,2,3,4]
y=[4,5,6,7]
z=[]
for i,j in zip(x,y):
    z.append(i+j)
print(z)

[5, 7, 9, 11]


In [3]:
#ufunc add() to return sum of two lists vertical calculation
import numpy as np
x=[1,2,3,4]
y=[4,5,6,7]
z=np.add(x,y)

# ufunc create function

In [6]:
#To create ufunc---------->frompyfunc() method
def fun(x,y):
    return x+y
#frompyfunc method takes 3 arguments--->1)normal function   2)no of input parameters   3)no of output parameters

add=np.frompyfunc(fun,2,1)
print(add([1,2,3,4],[5,6,7,8]))

[6 8 10 12]


In [7]:
print(type(add))

<class 'numpy.ufunc'>


In [8]:
if type(np.add==np.ufunc):
    print("ufunc")
else:
    print("not a ufunc")

ufunc


# ufunc simple arithmetic function

In [ ]:
#+,-,*,/,%,**

#functions available are add(),subtract(),multiply(),divide(),mod(),remainder(),power(),divmode()-->for getting both quotient and 
#mod

#Absolute Functions--->absolute(),abs()

In [ ]:
#scalar means 0-d

#vector means 1-d

#matrix means 2-d

In [ ]:
#Scalar: A scalar is a single numerical value, without any direction or dimension. It is considered a zero-dimensional object
#because it doesn't have length, width, or height. Examples include individual numbers like 5, -2.7, or π.
#Vector: A vector is an ordered collection of scalar values. It represents a quantity with both magnitude and direction and is 
#typically arranged in a one-dimensional array. Vectors are one-dimensional because they can be described by a single dimension 
#(e.g., a list of numbers). Examples include [3, 7, -2], [0, 1, 0], or [π, 2.5, 1.1].
#Matrix: A matrix is a two-dimensional array of scalar values, arranged in rows and columns. It represents a collection of 
#vectors or a transformation of space. Each element in a matrix is identified by its row and column indices. Examples include [[1, 2], [3, 4]], [[-1, 0, 1], [2, -2, 3]], or [[π, 0], [0, 2.5]].

In [10]:
v1=[1,2,3,4]
v2=[5,6,7,8]

[ 6  8 10 12]


In [13]:
addition=np.add(v1,v2)

subtraction=np.subtract(v1,v2)

multiplication=np.multiply(v1,v2)

divison=np.divide(v1,v2)

modulus=np.mod(v1,v2)

remainder=np.remainder(v1,v2)

rem=np.mod(v1,v2)

power=np.power(v1,v2)

Quotient_and_Mod=np.divmod(v1,v2)

absolute=np.abs(v1)

abs1=np.absolute(v2)


In [15]:
print(addition,subtraction,multiplication,divison,modulus,remainder,rem,power,Quotient_and_Mod,absolute,abs1)

[ 6  8 10 12] [-4 -4 -4 -4] [ 5 12 21 32] [0.2        0.33333333 0.42857143 0.5       ] [1 2 3 4] [1 2 3 4] [1 2 3 4] [    1    64  2187 65536] (array([0, 0, 0, 0]), array([1, 2, 3, 4])) [1 2 3 4] [5 6 7 8]


# ufunc Rounding Decimals

In [ ]:
#There are 5 ways to round off decimals in numpy

In [ ]:
#1)truncation
#2)fix
#3)rounding
#4)ceil
#5)floor

In [16]:
#truncate and fix removes the decimal values and return float values with .

arr=np.fix([-3.654,3.4543])
print(arr)

[-3.  3.]


In [18]:
#trunc
arr=np.trunc([-3.654,3.4543])
print(arr)

[-3.  3.]


In [26]:
#Rounding--------->around() method--->if .14 then will not increment by 1 if >=5 then increments by 1
arr=np.around(3.14,1)
print(arr)

3.1


In [27]:
#floor()
#the floor function rounds off to lowest integer but returns float value with decimal point

arr=np.floor([1.34,2.3])
print(arr)

[1. 2.]


In [28]:
#ceil()
#theceil function rounds off to highest integer but returns float value with decimal point

arr=np.ceil([1.34,2.3])
print(arr)

[2. 3.]


# NumPy Logs

In [ ]:
#NumPy provides functions to perform log at base 2,e,10

In [29]:
#log at Base2
#Use the log2() function to perform log at the base 2.
arr=np.array([1,2,3,4,5])
print(np.log(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [30]:
#Log at Base 10
#Use the log10() function to perform log at the base 10.
arr=np.array([1,2,3,4,5])
print(np.log10(arr))

[0.         0.30103    0.47712125 0.60205999 0.69897   ]


In [32]:
#Natural Log, or Log at Base e
#Use the log() function to perform log at the base e.
arr=np.arange(1,100)
print(np.log(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509 2.39789527 2.48490665
 2.56494936 2.63905733 2.7080502  2.77258872 2.83321334 2.89037176
 2.94443898 2.99573227 3.04452244 3.09104245 3.13549422 3.17805383
 3.21887582 3.25809654 3.29583687 3.33220451 3.36729583 3.40119738
 3.4339872  3.4657359  3.49650756 3.52636052 3.55534806 3.58351894
 3.61091791 3.63758616 3.66356165 3.68887945 3.71357207 3.73766962
 3.76120012 3.78418963 3.80666249 3.8286414  3.8501476  3.87120101
 3.8918203  3.91202301 3.93182563 3.95124372 3.97029191 3.98898405
 4.00733319 4.02535169 4.04305127 4.06044301 4.07753744 4.09434456
 4.11087386 4.12713439 4.14313473 4.15888308 4.17438727 4.18965474
 4.20469262 4.21950771 4.2341065  4.24849524 4.26267988 4.27666612
 4.29045944 4.30406509 4.31748811 4.33073334 4.34380542 4.35670883
 4.36944785 4.38202663 4.39444915 4.40671925 4.41884061 4.4308168
 4.44265126 4.4543473  4.46590812 4.47733681 4.48863637 4.49980

In [35]:
#Log at Any Base
#NumPy does not provide any function to take log at any base, so we can use the frompyfunc() function along with inbuilt 
#function math.log() with two input parameters and one output parameter:
from math import log
nlog=np.frompyfunc(log,2,1)
print(nlog(100,15))

1.7005483074552052


In [ ]:
#Summations
#What is the difference between summation and addition?

#Addition is done between two arguments whereas summation happens over n elements.

In [36]:
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])

In [37]:
##addition
print(add(arr1,arr2))

[6 8 10 12]


In [44]:
##summation
print(sum(arr1,arr2))

[15 16 17 18]


In [47]:
new_arr=np.sum([arr1,arr2],axis=1)
print(new_arr)#--->axis=1 horizontal  --->axis=0-->vertical

[10 26]


In [ ]:
#Cummulative Sum
#Cummulative sum means partially adding the elements in array.

#E.g. The partial sum of [1, 2, 3, 4] would be [1, 1+2, 1+2+3, 1+2+3+4] = [1, 3, 6, 10].

#Perfom partial sum with the cumsum() function.

In [42]:
##cummalative sum----------->takes only one argument
print(np.cumsum(add(arr1,arr2)))

[6 14 24 36]


# ufunc Product

In [56]:
 # prod() method
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
new_arr=np.prod(([arr1,arr2]))
print(new_arr)

40320


In [57]:
 # prod() method over axis=1
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
new_arr=np.prod(([arr1,arr2]),axis=1)
print(new_arr)

[  24 1680]


In [59]:
 # prod() method over axis=0
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
new_arr=np.prod(([arr1,arr2]),axis=0)
print(new_arr)

[ 5 12 21 32]


In [61]:
#Cummulative Product
#Cummulative product means taking the product partially.

#E.g. The partial product of [1, 2, 3, 4] is [1, 1*2, 1*2*3, 1*2*3*4] = [1, 2, 6, 24]

#Perfom partial sum with the cumprod() function.

arr=np.array([1,2,3,4])
print(np.cumprod(arr))

[ 1  2  6 24]


# ufunc Differences

In [71]:
#Differences
#A discrete difference means subtracting two successive elements.

#E.g. for [1, 2, 3, 4], the discrete difference would be [2-1, 3-2, 4-3] = [1, 1, 1]

#To find the discrete difference, use the diff() function.

arr=np.array([1,2,3,4,5,6])
new_arr=np.diff((arr))
print(new_arr)

[1 1 1 1 1]


In [72]:
#We can perform this operation repeatedly by giving parameter n.
new_arr=np.diff((arr),n=0)
print(new_arr)

[1 2 3 4 5 6]


# ufunc LCM 

In [73]:
num1=4
num2=6
x=np.lcm(num1,num2)
print(x)

12


In [75]:
#The above is used to calculate lcm only for two numbers only.
#so to calculate LCM of an array we need to use lcm.reduce() function

In [77]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30])
print(np.lcm.reduce(arr))

-1526361136


# ufunc GCD Greatest Common Denominator

In [78]:
num1 = 6
num2 = 9

x = np.gcd(num1, num2)

print(x)

3


In [79]:
#The above is used to calculate hcf only for two numbers only.
#so to calculate hcf of an array we need to use lcm.reduce() function

In [80]:
arr = np.array([1,2,3,4,5])

x = np.gcd.reduce(arr)

print(x)

1


# ufunc Trignometric Functions

In [ ]:
# Numpy Provides the ufuncs=---->sin(),cos(),tan(),

#To find degree to radians
#deg2rad(),rad2deg(),

#To find angles

#arcsin(),arccos(),arctan(),

#To find hypotenuse
#hypot()

In [ ]:
#Hyperbolic Functions

#sinh(),cosh(),tanh()

#to find angles
#arcsinh(),arccosh(),arctanh()

# ufunc set Operations

In [ ]:
#A set in mathematics is a collection of unique elements.

#Sets are used for operations involving frequent intersection, union and difference operations.


In [ ]:
#Create Sets in NumPy
#We can use NumPys unique() method to find unique elements from any array. s.

In [ ]:
#unique() method

In [81]:
arr = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])

x = np.unique(arr)

print(x)

[1 2 3 4 5 6 7]


In [ ]:
#Finding Union
#To find the unique values of two arrays, use the union1d() method.

In [82]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

newarr = np.union1d(arr1, arr2)

print(newarr)

[1 2 3 4 5 6]


In [ ]:
#Finding Intersection
#To find only the values that are present in both arrays, use the intersect1d() method.

In [83]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

newarr = np.intersect1d(arr1, arr2, assume_unique=True)

print(newarr)

[3 4]


In [ ]:
#assume_unique
#intersect1d() method takes an optional argument assume_unique, which if set to True can speed up computation.
#It should always be set to True when dealing with sets.

In [ ]:
#Finding Difference
#To find only the values in the first set that is NOT present in the seconds set, use the setdiff1d() method.

In [84]:
set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])

newarr = np.setdiff1d(set1, set2, assume_unique=True)

print(newarr)

[1 2]


In [ ]:
#the setdiff1d() method takes an optional argument assume_unique, which if set to True can speed up computation.
#It should always be set to True when dealing with sets.

In [ ]:
#Finding Symmetric Difference
#To find only the values that are NOT present in BOTH sets, use the setxor1d() method.

In [85]:
set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])

newarr = np.setxor1d(set1, set2, assume_unique=True)

print(newarr)

[1 2 5 6]


In [ ]:
#the setxor1d() method takes an optional argument assume_unique, which if set to True can speed up computation. 
#It should always be set to True when dealing with sets.