# NumPy Array Creation

In [2]:
#importing numpy library with alias name
import numpy as np

In [3]:
#Numpy creation(ndarray object)
arr1=np.array([1,2,3,4])#creation of array by passing list of integers as a argument to array object.

arr2=np.array((1,2,3,4))#creation of array by passing tuple of integers as a argument to array object.

print(arr1,arr2)

[1 2 3 4] [1 2 3 4]


In [6]:
for i in arr1:
    print(i,end=" ")

1 2 3 4 

In [12]:
for i in range(len(arr1)):
    print(i,"------>",arr1[i])

0 ------> 1
1 ------> 2
2 ------> 3
3 ------> 4


In [15]:
for i in np.nditer(arr1):#nditer is an object provided by numpy to iterate over an array.
    print(i,end=" ")

1 2 3 4 

In [17]:
for ind,i in np.ndenumerate(arr1):#ndenumerate is an object provided by numpy to iterate over an array(the array is unpacked providing index separately).
    print(ind,"--->",i)

(0,) ---> 1
(1,) ---> 2
(2,) ---> 3
(3,) ---> 4


In [ ]:
#the element is of an array is originally unknown, but its size is known. Hence, NumPy offers several functions to create arrays
#with initial placeholder content. These minimize the necessity of growing arrays, an expensive operation. For example: np.zeros,
#np.ones, np.full, np.empty, etc.

In [18]:
arr3=np.zeros((3,3))
print(arr3)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [19]:
arr4=np.ones((3,3))
print(arr4)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [20]:
arr5=np.full((3,3),5)
print(arr5)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [10]:
#This function create a new array of given shape and type, without initializing value.
import numpy as np
arr=np.empty((4,3),dtype=np.int32,order='C')
print(arr)

[[6029358 6619204 6881398]
 [6619235 4718684 7471201]
 [6553700 7536745 5636203]
 [7077999 7143541 3604581]]


In [22]:
#to create an array of random values
arr6=np.random.random((3,3))
print(arr6)
#this will create random values of floating point numbers between 0 and 1 of shape 3*3

[[0.56888076 0.48939362 0.36347654]
 [0.30432491 0.24978393 0.9780741 ]
 [0.90992303 0.57680094 0.59632401]]


In [28]:
#to create an random values of integer type
arr7=np.random.randint(0,10,(3,3),dtype='int32')
print(arr7)
##this will create random values of integer numbers between 0 and 10 of shape 3*3

[[8 8 9]
 [7 2 3]
 [8 6 2]]


In [32]:
#np.arange is used to create evenly spaced numbered arrays of specified size with in a given interval
#The function signature is np.arange(start, stop, step)
arr8=np.arange(1,10,1)
print(arr8)

[1 2 3 4 5 6 7 8 9]


In [34]:
#to reshape the above array to any size,the created array can be reshaped using reshape method
arr9=arr8.reshape(3,3)
print(arr9)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [45]:
#linspace:it returns evenly spaced integers with in a given interval of specified number of points
arr10=np.linspace(1,10,40,dtype='int32')
print(arr10)

[ 1  1  1  1  1  2  2  2  2  3  3  3  3  4  4  4  4  4  5  5  5  5  6  6
  6  6  7  7  7  7  7  8  8  8  8  9  9  9  9 10]


In [ ]:
"""np.arange(start, stop, step): Generates values from start to stop (exclusive) with a constant step size step.

np.linspace(start, stop, num): Generates num evenly spaced values from start to stop (inclusive).

In essence, np.arange is more suitable when you want to specify the step size explicitly, while np.linspace is more convenient

when you want to specify the number of points within the range."""

In [48]:
#flattening a multidimensional to a 1-dimensional array can be done by using flatten() method.
arr11=np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
flattened_arr=arr11.flatten()
print(flattened_arr)
#flatten() creates a new copy of the array, so any modifications to the flattened array won't affect the original.

[1 2 3 4 5 6 7 8 9]


In [51]:
#flattening a multidimensional to a 1-dimensional array can be done by using ravel() method.
arr12 = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
raveled_arr = arr12.ravel()
print(raveled_arr)
#ravel() returns a flattened view of the array. It doesn't create a new copy, so modifications to the flattened array will also
#affect the original array.

[1 2 3 4 5 6 7 8 9]


# NumPy Array Indexing

In [ ]:
#NumPy array indexing is important for analyzing and manipulating the array object.
#Slicing: Just like lists in Python, NumPy arrays can be sliced. As arrays can be multidimensional, we need to specify a slice 
        #for each dimension of the array.
#Integer array indexing: In this method, lists are passed for indexing for each dimension. One-to-one mapping of corresponding 
                        #elements is done to construct a new arbitrary array.
#Boolean array indexing: This method is used when we want to pick elements from the array which satisfy some condition.

In [ ]:
#hyper layers
#layers
#start
#end
#arr[start:end:step]

In [54]:
arr=np.array([1,2,3,4])
print(arr[0:4])

[1 2 3 4]


In [56]:
#Boolean Array Indexing Eample
arr13=np.array([1,2,3,4,5,6,7,8,9,10])
condition=arr13>0
temp=arr13[condition]
print(temp)

[ 1  2  3  4  5  6  7  8  9 10]


# NumPy Basic Operations

In [58]:
#Operations on single numpy array

arr14=np.array([1,2,3,4])
arr15=arr14+1
print(arr15)

[2 3 4 5]


In [59]:
arr16=arr15-1
print(arr16)

[1 2 3 4]


In [60]:
arr17=arr16*1
print(arr17)

[1 2 3 4]


In [64]:
print(arr17**4)

[  1  16  81 256]


In [66]:
arr1=np.array([[1,2,3,4],[5,6,7,8]])
arr2=np.array([[9,10,11,12],[13,14,15,16]])

In [68]:
arr3=arr1+arr2
print(arr3)

[[10 12 14 16]
 [18 20 22 24]]


In [70]:
arr4=arr2-arr1
print(arr4)

[[8 8 8 8]
 [8 8 8 8]]


In [71]:
arr5=arr2/arr1
print(arr5)

[[9.         5.         3.66666667 3.        ]
 [2.6        2.33333333 2.14285714 2.        ]]


In [72]:
arr6=arr2**arr1
print(arr6)

[[        9       100      1331     20736]
 [   371293   7529536 170859375         0]]


In [73]:
arr7=arr2%arr1
print(arr7)

[[0 0 2 0]
 [3 2 1 0]]


In [74]:
arr8=arr2//arr1
print(arr8)

[[9 5 3 3]
 [2 2 2 2]]


# NumPy Unary Operators

In [75]:
arr=np.array([1,2,3,4,5,6,7,8])
print(arr.max())

8


In [76]:
print(arr.min())

1


In [82]:
print(arr.sum())

36


In [80]:
print(arr.cumsum(axis=0))

[ 1  3  6 10 15 21 28 36]


In [81]:
print(arr.cumprod())

[    1     2     6    24   120   720  5040 40320]


# NumPy Sorting Arrays

In [86]:
a=np.array([[1,4,2],[3,6,8]])
print(np.sort(a,axis=1,kind='mergesort'))

#axis=1 means sorts horizontally 
#axis=0 means sorts vertically

[[1 2 4]
 [3 6 8]]


In [87]:
# Example to show sorting of structured array 
# set alias names for dtypes 
dtypes = [('name', 'S10'), ('grad_year', int), ('cgpa', float)] 
  
# Values to be put in array 
values = [('Hrithik', 2009, 8.5), ('Ajay', 2008, 8.7),  
           ('Pankaj', 2008, 7.9), ('Aakash', 2009, 9.0)] 
             
# Creating array 
arr = np.array(values, dtype = dtypes) 
print ("\nArray sorted by names:\n", 
            np.sort(arr, order = 'name')) 
              
print ("Array sorted by graduation year and then cgpa:\n", 
                np.sort(arr, order = ['grad_year', 'cgpa'])) 


Array sorted by names:
 [(b'Aakash', 2009, 9. ) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Pankaj', 2008, 7.9)]
Array sorted by graduation year and then cgpa:
 [(b'Pankaj', 2008, 7.9) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Aakash', 2009, 9. )]


# Rank of an array is it's Depth (3*3 matrix has rank of 3, 2*2 matrix has 2 similarly for 1*1 has 1)

In [2]:
#list to array
import numpy as np
list=[1,2,3,4]
arr=np.array(list)
print(arr)

[1 2 3 4]


In [5]:
list1=[1,2,3,4]
list2=[5,6,7,8]
list3=[9,10,11,12]
arr=np.array([list1,list2,list3])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


# NumPy DataTypes

In [11]:
#By default python has data types like integer,float,complex.boolean,strings

# Data Types in NumPy
i-integer
f-float
u-unsigned integer
c-complex float
b-boolean
m-timedelta
M-datetime
O-Object
S-String
U-Unicode String
V-void

In [14]:
# astype(datatype) function
arr=np.array([1.0,2.0,3.0,4.0])
print(arr)
arr1=arr.astype(int)
print(arr1)
arr1=arr.astype(bool)
print(arr1)

[1. 2. 3. 4.]
[1 2 3 4]
[ True  True  True  True]


In [15]:
#copy vs view functions
arr1=np.array([1,2,3,4])
arr2=np.copy(arr1)
print(arr2)
#any changes made to arr2 will not affect arr1

[1 2 3 4]


In [17]:
arr3=np.array([1,2,3,4])
arr4=arr3.view()
print(arr4)
#any changes made to arr2 will affect arr1
arr4[3]=9
print(arr3,arr4)

[1 2 3 4]
[1 2 3 9] [1 2 3 9]


In [19]:
#to check whether an array own the data (copy owns the data independently whereas the view does not owns the data independently)
#to check that we will be using the method base
#The copy returns None.
#The view returns the original array.

print(arr4.base)
print(arr2.base)

[1 2 3 9]
None


In [20]:
#to know the shape of the array
print(arr.shape)

(4,)


In [30]:
#to reshape the array from 1-d to 2-d and viceversa etc..
arr=np.array([1,2,3,4,5,6,7,8])
arr1=np.array_split(arr,3)
print(arr1)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8])]


In [32]:
#vstack,hstack,dstack,vsplit,hsplit,dsplit

In [33]:
#Numpy searching arrays
arr=np.array([1,2,3,4,5])
arr1=np.where(arr%2==1)
print(arr1)

(array([0, 2, 4], dtype=int64),)


In [37]:
#searchsorted returns the index of the array
arr=np.array([1,2,3,4,5,6,7,8,9,10])
arr_index=np.searchsorted(arr,7)#####this function by default searches from right
print(arr_index)
arr_index=np.searchsorted(arr,7,side='right');
print(arr_index)
#To search from right side use side='right'

6
7


In [39]:
#multiple values can be searched
arr_index=np.searchsorted(arr,[1,3,4,7,10],side='left')
print(arr_index)

[0 2 3 6 9]


In [45]:
#sorting an array
Arr=arr[-1::-1]
print(Arr)
Arr=np.sort(arr)
print(arr,Arr)

[10  9  8  7  6  5  4  3  2  1]
[ 1  2  3  4  5  6  7  8  9 10] [ 1  2  3  4  5  6  7  8  9 10]


In [48]:
#Filtering an array is done by using boolean indexing list.
arr=np.array([1,2,3,4,5,6])
bool_list=[True,False,True,False,True,False]
new_arr=arr[bool_list]
print(new_arr)

[1 3 5]


In [50]:
#creating boolean indexing list directly from array
arr=np.array([10,39,84,84,84,59,37,48,56,39,38])
filter_array=arr>20
arr_new=arr[filter_array]
print(arr_new)

[39 84 84 84 59 37 48 56 39 38]
